### ISSUE TITLE
Update dependency com.esotericsoftware:kryo to 5.1.0

### ISSUE THREAD

**Issue by tapioko** [conveyal/kryo-tools#6]
Version 5.1.0 has a dependency to newer version of objenesis, which fixes this:
```
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.objenesis.instantiator.basic.ObjectStreamClassInstantiator (file:/C:/proj/otp/otp-2.1.0-SNAPSHOT-shaded.jar) to method java.io.ObjectStreamClass.newInstance()
WARNING: Please consider reporting this to the maintainers of org.objenesis.instantiator.basic.ObjectStreamClassInstantiator
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
```

Then OpenTripPlanner (which in turn depends on kryo-tools) can be run with Java 16, because Java 16 does not by default just log a warning, but aborts execution.

https://mvnrepository.com/artifact/com.esotericsoftware/kryo/5.1.0

**Comment by abyrd** [comment]
I just released kryo-tools v1.4.0 which uses Kryo 5 and should fix this. It will be used in OTP v2.1.
